version: 0.1.{build}

branches:
  only:
    - master

image: Visual Studio 2019

configuration: Release

platform: Any CPU
assembly_info:
  patch: true
  file: 'LibForge\*\Properties\AssemblyInfo.*'
  assembly_version: '{version}.0'
  assembly_file_version: '{version}.0'
  assembly_informational_version: '{version}.0'

install:
- cmd: git submodule update --init --recursive

before_build:
- cmd: nuget restore LibForge/LibForge.sln

build:
  project: LibForge/LibForge.sln
  parallel: true
  verbosity: minimal

after_build:
 - >
   7z a LibForge-%APPVEYOR_BUILD_VERSION%.zip 
   %APPVEYOR_BUILD_FOLDER%\LibForge\ForgeTool\bin\Release\LibForge.dll
   %APPVEYOR_BUILD_FOLDER%\LibForge\ForgeTool\bin\Release\MidiCS.dll
   %APPVEYOR_BUILD_FOLDER%\LibForge\ForgeToolGUI\bin\Release\GameArchives.dll
   %APPVEYOR_BUILD_FOLDER%\LibForge\ForgeToolGUI\bin\Release\LibOrbisPkg.dll
   %APPVEYOR_BUILD_FOLDER%\LibForge\ForgeToolGUI\bin\Release\DtxCS.dll
   %APPVEYOR_BUILD_FOLDER%\README.md
   %APPVEYOR_BUILD_FOLDER%\LICENSE.txt
 - >
   7z a ForgeTool-%APPVEYOR_BUILD_VERSION%.zip 
   %APPVEYOR_BUILD_FOLDER%\LibForge\ForgeTool\bin\Release\ForgeTool.exe
   %APPVEYOR_BUILD_FOLDER%\LibForge\ForgeTool\bin\Release\LibForge.dll
   %APPVEYOR_BUILD_FOLDER%\LibForge\ForgeTool\bin\Release\MidiCS.dll
   %APPVEYOR_BUILD_FOLDER%\LibForge\ForgeToolGUI\bin\Release\GameArchives.dll
   %APPVEYOR_BUILD_FOLDER%\LibForge\ForgeToolGUI\bin\Release\LibOrbisPkg.dll
   %APPVEYOR_BUILD_FOLDER%\LibForge\ForgeToolGUI\bin\Release\DtxCS.dll
   %APPVEYOR_BUILD_FOLDER%\README.md
   %APPVEYOR_BUILD_FOLDER%\LICENSE.txt
 - >
   7z a ForgeToolGUI-%APPVEYOR_BUILD_VERSION%.zip 
   %APPVEYOR_BUILD_FOLDER%\LibForge\ForgeTool\bin\Release\ForgeTool.exe
   %APPVEYOR_BUILD_FOLDER%\LibForge\ForgeTool\bin\Release\LibForge.dll
   %APPVEYOR_BUILD_FOLDER%\LibForge\ForgeTool\bin\Release\MidiCS.dll
   %APPVEYOR_BUILD_FOLDER%\LibForge\ForgeToolGUI\bin\Release\GameArchives.dll
   %APPVEYOR_BUILD_FOLDER%\LibForge\ForgeToolGUI\bin\Release\LibOrbisPkg.dll
   %APPVEYOR_BUILD_FOLDER%\LibForge\ForgeToolGUI\bin\Release\OpenTK.dll
   %APPVEYOR_BUILD_FOLDER%\LibForge\ForgeToolGUI\bin\Release\OpenTK.GLControl.dll
   %APPVEYOR_BUILD_FOLDER%\LibForge\ForgeToolGUI\bin\Release\DtxCS.dll
   %APPVEYOR_BUILD_FOLDER%\LibForge\ForgeToolGUI\bin\Release\ForgeToolGUI.exe
   %APPVEYOR_BUILD_FOLDER%\README.md
   %APPVEYOR_BUILD_FOLDER%\LICENSE.txt
artifacts:
- path: LibForge-%APPVEYOR_BUILD_VERSION%.zip
- path: ForgeTool-%APPVEYOR_BUILD_VERSION%.zip
- path: ForgeToolGUI-%APPVEYOR_BUILD_VERSION%.zip